# --- Paramètres de base ---
title: Cassian - Mathématiques
email: dupontcassian@gmail.com
description: >-
  Mon site.
baseurl: ""
url: "https://Cassian-09.github.io"

# --- Thème et plugins Jekyll ---
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
