# --- Paramètres de base ---
title: Prénom et Nom
email: dupontcassian@gmail.com
description: >-

baseurl: ""
url: "https://Cassian-09.github.io"

# --- Thème et plugins Jekyll ---
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
